// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbD7-53dZnerI7rSYkAn7f_tSWXlLIl6s',
    appId: '1:348046556049:web:f7a5a1deeb614c24057830',
    messagingSenderId: '348046556049',
    projectId: 'bytelogikgame',
    authDomain: 'bytelogikgame.firebaseapp.com',
    storageBucket: 'bytelogikgame.firebasestorage.app',
    measurementId: 'G-LGH6W8KJNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCceHa6bvlpCvqy7cN0RiBGGmTZ8mZs_6k',
    appId: '1:348046556049:android:acbe621180b6bb2a057830',
    messagingSenderId: '348046556049',
    projectId: 'bytelogikgame',
    storageBucket: 'bytelogikgame.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJJv7OHvxoL6xGg9DR5E58C0zK9fGh_g',
    appId: '1:348046556049:ios:9706d04982212a59057830',
    messagingSenderId: '348046556049',
    projectId: 'bytelogikgame',
    storageBucket: 'bytelogikgame.firebasestorage.app',
    iosBundleId: 'com.example.bytelogikgameinterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJJv7OHvxoL6xGg9DR5E58C0zK9fGh_g',
    appId: '1:348046556049:ios:9706d04982212a59057830',
    messagingSenderId: '348046556049',
    projectId: 'bytelogikgame',
    storageBucket: 'bytelogikgame.firebasestorage.app',
    iosBundleId: 'com.example.bytelogikgameinterview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbD7-53dZnerI7rSYkAn7f_tSWXlLIl6s',
    appId: '1:348046556049:web:48dffd4598681c4c057830',
    messagingSenderId: '348046556049',
    projectId: 'bytelogikgame',
    authDomain: 'bytelogikgame.firebaseapp.com',
    storageBucket: 'bytelogikgame.firebasestorage.app',
    measurementId: 'G-C48C5VGK9G',
  );
}
